version: '3.7'

services:

  postgres:
    image: postgres:10
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    - "POSTGRES_DB=postgres"

volumes:
  postgres:
